const bindings = [
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Zoom' },
    label: 'Zoom',
    keys: ['z'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Pan' },
    label: 'Pan',
    keys: ['p'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'WindowLevel' },
    label: 'Window Level',
    keys: ['w'],
    isEditable: true,
  },
  // The measurement tools
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Length' },
    label: 'Length',
    keys: ['d'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Angle' },
    label: 'Angle',
    keys: ['a'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Bidirectional' },
    label: 'Bidirectional',
    keys: ['b'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'ArrowAnnotate' },
    label: 'Arrow annotation',
    keys: ['f'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'EllipticalROI' },
    label: 'Ellipse',
    keys: ['e'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'CircleROI' },
    label: 'Circle',
    keys: ['o'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'RectangleROI' },
    label: 'Rectangle',
    keys: ['t'],
    isEditable: true,
  },
  // Strumenti di interazione/ispezione
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'StackScroll' },
    label: 'Stack scroll',
    keys: ['s'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Magnify' },
    label: "Magnify",
    keys: ['m'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Probe' },
    label: 'Probe',
    keys: ['q'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'WindowLevelRegion' },
    label: 'Window level over a region',
    keys: ['n'],
    isEditable: true,
  },
  // The further measurement and annotation tools
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'CobbAngle' },
    label: 'Cobb angle',
    keys: ['k'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'CalibrationLine' },
    label: 'Calibration',
    keys: ['u'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'PlanarFreehandROI' },
    label: 'Freehand ROI',
    keys: ['g'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'SplineROI' },
    label: 'ROI spline',
    keys: ['y'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'LivewireContour' },
    label: 'Livewire contour',
    keys: ['j'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'UltrasoundDirectionalTool' },
    label: 'Ultrasound directional',
    keys: ['x'],
    isEditable: true,
  },
  {
    commandName: 'scaleUpViewport',
    label: 'Zoom in',
    keys: ['+'],
    isEditable: true,
  },
  {
    commandName: 'scaleDownViewport',
    label: 'Zoom out',
    keys: ['-'],
    isEditable: true,
  },
  {
    commandName: 'fitViewportToWindow',
    label: 'Fit to window',
    keys: ['='],
    isEditable: true,
  },
  {
    commandName: 'rotateViewportCW',
    label: 'Rotate right',
    keys: ['r'],
    isEditable: true,
  },
  {
    commandName: 'rotateViewportCCW',
    label: 'Rotate left',
    keys: ['l'],
    isEditable: true,
  },
  {
    commandName: 'flipViewportHorizontal',
    label: 'Flip horizontally',
    keys: ['h'],
    isEditable: true,
  },
  {
    commandName: 'flipViewportVertical',
    label: 'Flip vertically',
    keys: ['v'],
    isEditable: true,
  },
  {
    commandName: 'toggleCine',
    label: 'Cine',
    keys: ['c'],
  },
  {
    commandName: 'invertViewport',
    label: 'Invert',
    keys: ['i'],
    isEditable: true,
  },
  {
    commandName: 'incrementActiveViewport',
    label: 'Next viewport',
    keys: ['right'],
    isEditable: true,
  },
  {
    commandName: 'decrementActiveViewport',
    label: 'Previous viewport',
    keys: ['left'],
    isEditable: true,
  },
  {
    commandName: 'updateViewportDisplaySet',
    commandOptions: {
      direction: -1,
    },
    label: 'Previous series',
    keys: ['pageup'],
    isEditable: true,
  },
  {
    commandName: 'updateViewportDisplaySet',
    commandOptions: {
      direction: 1,
    },
    label: 'Next series',
    keys: ['pagedown'],
    isEditable: true,
  },
  {
    commandName: 'nextStage',
    context: 'DEFAULT',
    label: 'Next stage',
    keys: ['.'],
    isEditable: true,
  },
  {
    commandName: 'previousStage',
    context: 'DEFAULT',
    label: 'Previous stage',
    keys: [','],
    isEditable: true,
  },
  {
    commandName: 'nextImage',
    label: 'Next image',
    keys: ['down'],
    isEditable: true,
  },
  {
    commandName: 'previousImage',
    label: 'Previous image',
    keys: ['up'],
    isEditable: true,
  },
  {
    commandName: 'firstImage',
    label: 'First image',
    keys: ['home'],
    isEditable: true,
  },
  {
    commandName: 'lastImage',
    label: 'Last image',
    keys: ['end'],
    isEditable: true,
  },
  {
    commandName: 'resetViewport',
    label: 'Reset',
    keys: ['space'],
    isEditable: true,
  },
  {
    commandName: 'cancelMeasurement',
    label: 'Delete the last measurement',
    keys: ['esc'],
  },
  // Window level presets: the active series' DICOM presets come first, then the
  // configured ones. Key N applies the Nth of the combined list.
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 0 },
    label: 'Preset W/L 1',
    keys: ['1'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 1 },
    label: 'Preset W/L 2',
    keys: ['2'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 2 },
    label: 'Preset W/L 3',
    keys: ['3'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 3 },
    label: 'Preset W/L 4',
    keys: ['4'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 4 },
    label: 'Preset W/L 5',
    keys: ['5'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 5 },
    label: 'Preset W/L 6',
    keys: ['6'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 6 },
    label: 'Preset W/L 7',
    keys: ['7'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 7 },
    label: 'Preset W/L 8',
    keys: ['8'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 8 },
    label: 'Preset W/L 9',
    keys: ['9'],
  },
  {
    commandName: 'deleteActiveAnnotation',
    label: 'Delete the annotation',
    keys: ['backspace'],
  },
  // Actions and switches, on Shift plus a key, so they do not clash with the tools.
  {
    commandName: 'hideInfoDicom',
    label: 'Hide the DICOM info',
    keys: ['shift+h'],
    isEditable: true,
  },
  {
    commandName: 'toggleMontage',
    label: 'Subgrid (auto)',
    keys: ['shift+g'],
    isEditable: true,
  },
  {
    commandName: 'toggleCrosshairs',
    commandOptions: { toolGroupIds: ['mpr'] },
    label: 'Crosshair (MPR)',
    keys: ['shift+x'],
    isEditable: true,
  },
  {
    commandName: 'showDownloadViewportModal',
    label: 'Capture the screen',
    keys: ['shift+s'],
    isEditable: true,
  },
  {
    commandName: 'toggleSynchronizer',
    commandOptions: { type: 'imageSlice' },
    label: 'Link images',
    keys: ['shift+y'],
    isEditable: true,
  },
  {
    commandName: 'toggleEnabledDisabledToolbar',
    commandOptions: { itemId: 'ReferenceLines' },
    label: 'Reference lines',
    keys: ['shift+l'],
    isEditable: true,
  },
  {
    commandName: 'zoomOneToOne',
    label: 'Zoom 1:1',
    keys: ['shift+z'],
    isEditable: true,
  },
  // after we have the ui for undo/redo, we can add these back in
  // {
  //   commandName: 'undo',
  //   label: 'Undo',
  //   keys: ['ctrl+z'],
  //   isEditable: true,
  // },
  // {
  //   commandName: 'redo',
  //   label: 'Redo',
  //   keys: ['ctrl+y'],
  //   isEditable: true,
  // },
];

export default bindings;
