const bindings = [
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Zoom' },
    label: 'Zoom',
    keys: ['z'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Pan' },
    label: 'Sposta',
    keys: ['p'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'WindowLevel' },
    label: 'Window Level',
    keys: ['w'],
    isEditable: true,
  },
  // Strumenti di misura
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Length' },
    label: 'Lunghezza',
    keys: ['d'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Angle' },
    label: 'Angolo',
    keys: ['a'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Bidirectional' },
    label: 'Bidirezionale',
    keys: ['b'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'ArrowAnnotate' },
    label: 'Freccia/Annotazione',
    keys: ['f'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'EllipticalROI' },
    label: 'Ellisse',
    keys: ['e'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'CircleROI' },
    label: 'Cerchio',
    keys: ['o'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'RectangleROI' },
    label: 'Rettangolo',
    keys: ['t'],
    isEditable: true,
  },
  // Strumenti di interazione/ispezione
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'StackScroll' },
    label: 'Scorrimento con mouse',
    keys: ['s'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Magnify' },
    label: "Lente d'ingrandimento",
    keys: ['m'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'Probe' },
    label: 'Sonda',
    keys: ['q'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'WindowLevelRegion' },
    label: 'Window Level su regione',
    keys: ['n'],
    isEditable: true,
  },
  // Strumenti di misura/annotazione aggiuntivi
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'CobbAngle' },
    label: 'Angolo di Cobb',
    keys: ['k'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'CalibrationLine' },
    label: 'Calibrazione',
    keys: ['u'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'PlanarFreehandROI' },
    label: 'ROI a mano libera',
    keys: ['g'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'SplineROI' },
    label: 'ROI spline',
    keys: ['y'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'LivewireContour' },
    label: 'Contorno Livewire',
    keys: ['j'],
    isEditable: true,
  },
  {
    commandName: 'setToolActiveToolbar',
    commandOptions: { toolName: 'UltrasoundDirectionalTool' },
    label: 'Ultrasuono direzionale',
    keys: ['x'],
    isEditable: true,
  },
  {
    commandName: 'scaleUpViewport',
    label: 'Zoom avanti',
    keys: ['+'],
    isEditable: true,
  },
  {
    commandName: 'scaleDownViewport',
    label: 'Zoom indietro',
    keys: ['-'],
    isEditable: true,
  },
  {
    commandName: 'fitViewportToWindow',
    label: 'Adatta alla finestra',
    keys: ['='],
    isEditable: true,
  },
  {
    commandName: 'rotateViewportCW',
    label: 'Ruota a destra',
    keys: ['r'],
    isEditable: true,
  },
  {
    commandName: 'rotateViewportCCW',
    label: 'Ruota a sinistra',
    keys: ['l'],
    isEditable: true,
  },
  {
    commandName: 'flipViewportHorizontal',
    label: 'Rifletti orizzontalmente',
    keys: ['h'],
    isEditable: true,
  },
  {
    commandName: 'flipViewportVertical',
    label: 'Rifletti verticalmente',
    keys: ['v'],
    isEditable: true,
  },
  {
    commandName: 'toggleCine',
    label: 'Cine',
    keys: ['c'],
  },
  {
    commandName: 'invertViewport',
    label: 'Inverti',
    keys: ['i'],
    isEditable: true,
  },
  {
    commandName: 'incrementActiveViewport',
    label: 'Viewport successiva',
    keys: ['right'],
    isEditable: true,
  },
  {
    commandName: 'decrementActiveViewport',
    label: 'Viewport precedente',
    keys: ['left'],
    isEditable: true,
  },
  {
    commandName: 'updateViewportDisplaySet',
    commandOptions: {
      direction: -1,
    },
    label: 'Serie precedente',
    keys: ['pageup'],
    isEditable: true,
  },
  {
    commandName: 'updateViewportDisplaySet',
    commandOptions: {
      direction: 1,
    },
    label: 'Serie successiva',
    keys: ['pagedown'],
    isEditable: true,
  },
  {
    commandName: 'nextStage',
    context: 'DEFAULT',
    label: 'Stage successivo',
    keys: ['.'],
    isEditable: true,
  },
  {
    commandName: 'previousStage',
    context: 'DEFAULT',
    label: 'Stage precedente',
    keys: [','],
    isEditable: true,
  },
  {
    commandName: 'nextImage',
    label: 'Immagine successiva',
    keys: ['down'],
    isEditable: true,
  },
  {
    commandName: 'previousImage',
    label: 'Immagine precedente',
    keys: ['up'],
    isEditable: true,
  },
  {
    commandName: 'firstImage',
    label: 'Prima immagine',
    keys: ['home'],
    isEditable: true,
  },
  {
    commandName: 'lastImage',
    label: 'Ultima immagine',
    keys: ['end'],
    isEditable: true,
  },
  {
    commandName: 'resetViewport',
    label: 'Ripristina',
    keys: ['space'],
    isEditable: true,
  },
  {
    commandName: 'cancelMeasurement',
    label: 'Elimina ultima misurazione',
    keys: ['esc'],
  },
  // Preset W/L: priorità ai preset DICOM della serie attiva, poi ai preset di
  // configurazione. Il tasto N attiva l'N-esimo preset combinato (DICOM + config).
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 0 },
    label: 'Preset W/L 1',
    keys: ['1'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 1 },
    label: 'Preset W/L 2',
    keys: ['2'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 2 },
    label: 'Preset W/L 3',
    keys: ['3'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 3 },
    label: 'Preset W/L 4',
    keys: ['4'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 4 },
    label: 'Preset W/L 5',
    keys: ['5'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 5 },
    label: 'Preset W/L 6',
    keys: ['6'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 6 },
    label: 'Preset W/L 7',
    keys: ['7'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 7 },
    label: 'Preset W/L 8',
    keys: ['8'],
  },
  {
    commandName: 'setWindowLevelPresetByIndex',
    commandOptions: { index: 8 },
    label: 'Preset W/L 9',
    keys: ['9'],
  },
  {
    commandName: 'deleteActiveAnnotation',
    label: 'Elimina annotazione',
    keys: ['backspace'],
  },
  // Azioni/interruttori (Shift+tasto, per non confliggere con gli strumenti).
  {
    commandName: 'hideInfoDicom',
    label: 'Nascondi info DICOM',
    keys: ['shift+h'],
    isEditable: true,
  },
  {
    commandName: 'toggleMontage',
    label: 'Sottogriglia (auto)',
    keys: ['shift+g'],
    isEditable: true,
  },
  {
    commandName: 'toggleCrosshairs',
    commandOptions: { toolGroupIds: ['mpr'] },
    label: 'Crosshair (MPR)',
    keys: ['shift+x'],
    isEditable: true,
  },
  {
    commandName: 'showDownloadViewportModal',
    label: 'Cattura schermo',
    keys: ['shift+s'],
    isEditable: true,
  },
  {
    commandName: 'toggleSynchronizer',
    commandOptions: { type: 'imageSlice' },
    label: 'Collega immagini',
    keys: ['shift+y'],
    isEditable: true,
  },
  {
    commandName: 'toggleEnabledDisabledToolbar',
    commandOptions: { itemId: 'ReferenceLines' },
    label: 'Linee di riferimento',
    keys: ['shift+l'],
    isEditable: true,
  },
  {
    commandName: 'zoomOneToOne',
    label: 'Zoom 1 a 1',
    keys: ['shift+z'],
    isEditable: true,
  },
  // after we have the ui for undo/redo, we can add these back in
  // {
  //   commandName: 'undo',
  //   label: 'Undo',
  //   keys: ['ctrl+z'],
  //   isEditable: true,
  // },
  // {
  //   commandName: 'redo',
  //   label: 'Redo',
  //   keys: ['ctrl+y'],
  //   isEditable: true,
  // },
];

export default bindings;
